### ISSUE TITLE
packages(index.coffee)

### ISSUE THREAD

**Issue by kou724** [jerfowler/ExpressBrunchJade#1]
Why isn't it reflected when I change packages(index.coffee)?

**Comment by jerfowler** [comment]
How are you changing it?

**Comment by kou724** [comment]
I use the text editor(Sublime Text 2).

I may not understand a right method.

**Comment by kou724** [comment]
How is it a right method to do?

**Comment by jerfowler** [comment]
I'm not quite understanding your English. Perhaps you could show me a code sample to help explain the problem?

**Comment by kou724** [comment]
Thank you for the reply.

ExpressBrunchJade\express\routes\index.coffee

I changed this file.

////////////BEFORE//////////////////////////////////////////////////////////////////////
packages = [
  { 
    name: 'Bootstrap'
    version: '2.2.2'
    desc: 'Sleek, intuitive, and powerful front-end framework for faster and easier web development. A 12-column responsive grid, dozens of components, JavaScript plugins, typography, form controls, and even a web-based Customizer to make Bootstrap your own.'
    url: 'http://twitter.github.com/bootstrap/' 
  },{
////////////////////////////////////////////////////////////////////////////////////////////////

//////////////AFTER//////////////////////////////////////////////////////////////////////////////
packages = [
  { 
    name: 'B'
    version: '1.1.1'
    desc: 'Sleek'
    url: 'http://google.com/' 
  },{
//////////////////////////////////////////////////////////////////////////////////////////////////////////

But display does not change.
To change the display, I must restart the server.

**Comment by jerfowler** [comment]
Brunch isn't designed to watch any of the express files for changes, so the server isn't auto-restarted. Also, the packages array is only created once, when index.coffee is requested from server.coffee. So, if you change the array after the file is saved, it isn't viewed again until after the server is restarted.

You could possibly use forever or some other program to monitor for changes to express files and restart brunch. I may look into doing something like this in the future. Cause, I agree having to restart brunch manually every time something changes with express is a total PIA.

However, with that said, the route that I provided really wasn't meant to be reused... It was just a quick way to setup an intro page and showcase the express server. You should focus on using backbone and create resources with express to which backbone interacts.

**Comment by jerfowler** [comment]
Just an FYI, I just added my own code to server.coffee that watches express server files for changes and it reloads the HTTP server automatically.
