### ISSUE TITLE
socket.io got something wrong

### ISSUE THREAD

**Issue by ghost** [jerfowler/ExpressBrunchJade#2]
when i 
brunch new <appname> --skeleton git://github.com/jerfowler/ExpressBrunchJade.git
brunch w -s
always get something wrong that 
    \node_modules\socket.io\lib\static.js:3333
       self.manager.log.debug....
      log has no method 'debug'

**Comment by jerfowler** [comment]
It was a problem with replacing the default socket.io logger with the brunch version, which doesn't have a debug function.

**Comment by ghost** [comment]
thank you, i like the skeleton
