### ISSUE TITLE
I try to start with app_router.coffee, nothing happened!

### ISSUE THREAD

**Issue by ghost** [jerfowler/ExpressBrunchJade#3]
I'am gradually familiar with the skeleton, and try to start with app_router.coffee,
module.exports = AppRouter = Backbone.Router.extend(
    routes:
        'hello': -> console.log 'hello'

)
nothing happened.
Have I  got something wrong?
or the best ,could you give me some example, so that I can learn from it.
Thanks.

**Comment by jerfowler** [comment]
I would take a look at the backbone documentation. The routes should point to an actual function name, not an anonymous function. The example noop should probably be replaced.

```
module.exports = AppRouter = Backbone.Router.extend(
    routes:
        'hello': 'hello'
    hello: -> console.log 'hello'
)
```

Then you can trigger the route by appending #/hello to the url in the browser or just /hello if pushState is true and the browser supports it. Either way, its probably a good idea to add the route to express as well, just point it to the default index route.

```
app.get '/hello', routes.index('Express', express.version)
```
